# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfc4afdcc7aedcda5a1b7e010d8e85fb7646d62283f03a92ff1777bf0589235e24934bb0124a885db17fc407a12d05f79efbc4a19781b76c4cdba10951d227c5

test:
  secret_key_base: 66635fad339fe30037ae1770fa66f0658f6b7387656a1497fc0325143e486c30367e1308220baf9961057a9b9928631c16931f4039d90d38df8ca81110b290cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
